### PR TITLE
fix: update icon for ocaml

### PR DESCRIPTION
**Pull request by benfaerber**
The current build uses the generic lambda icon for OCaml but Nerd Font supports the real OCaml logo.

### CODE REVIEW

**Review by Akmadan23 — APPROVED** [review]
Thank you very much!

**Comment by Akmadan23** [comment]
Sorry @benfaerber, may I ask you to sync your master branch? I'm receiving a CI failure email every day, and I don't know how to stop it... I don't even know if this would work, but it's worth a try. Thank you in advance

**Comment by benfaerber** [comment]
I sycned the fork. Is there anything else needed? I can delete the fork from my account if its still broken.

**Comment by Akmadan23** [comment]
It worked, thank you for helping me out!

**Pull request merged**
