### PR TITLE
fix(#261 #287): persist icon overrides when changing &background

### LINKED ISSUE #261: Overridden icon gets reset on colorscheme change
Overridden icons get reset when I change colorscheme.

**To reproduce:**

Configuration:

<details>
<summary><b>Click to expand</b></summary>

```lua
local root = vim.fn.fnamemodify(vim.fn.expand('$HOME') .. 'nvim-test-config', ':p')

for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
  vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ 'git', 'clone', '--filter=blob:none', 'https://github.com/folke/lazy.nvim.git', lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  { 'romgrk/barbar.nvim', config = true },
  {
    'kyazdani42/nvim-web-devicons',
    config = function()
      require('nvim-web-devicons').setup({
        override = {
          md = { icon = '', color = '#519aba', name = 'Markdown' }
        }
      })
    end,
  }
}

require('lazy').setup(plugins, {
  root = root .. '/plugins',
})
```

</details>

1. `nvim -u ~/nvim-test-config/init.lua testfile.md`
2. Notice the custom markdown icon in the top left
3. `:colorscheme blue`
4. `:e`
5. Markdown icon is back to the default

### PR DESCRIPTION
**Pull request by ribru17**
Fixes #261, #287

> [!NOTE]
> This PR does not address the problem of overrides being unaware of light/dark modes. They are applied universally still. This functionality will have to be implemented later, but this PR is better than nothing.

### CODE REVIEW

**Comment by Bekaboo** [comment]
> This PR does not address the problem of overrides being unaware of light/dark modes. They are applied universally still. This functionality will have to be implemented later, but this PR is better than nothing.

It will be great if we can just keep the current config structure and auto-generate the dark version (used with light bg) of the icons provided by users using the same logic that generates the dark icons for the default ones. I would like to help with this when I have time.

**Comment by ribru17** [comment]
I think ideally this should be done in another PR, I think getting this one merged on it's own will be good enough for many cases. From there I could try to make a PR for what you are saying. I could be wrong but it looks like the light mode icons are generated from the dark mode ones, given the darkening function in the scripts. Maybe we can just expose it publicly (it is private right now) and then use it directly in the refreshing function, detecting when the background is `light`?

**Comment by Bekaboo** [comment]
Yeah I mean I can make another PR for the problem of overrides being unaware of light/dark modes. Haven't gotten time to really look into this though, it will be cool if you are willing to do it!

**Comment by ribru17** [comment]
I think this PR is good to merge. I have a change waiting that will also update the highlights properly, but only for hex colors, not cterm. I'm not sure how to handle that one.

**Review by alex-courtis — APPROVED** [review]
Works nicely, many thanks for your contribution!

**Pull request merged**
