### PR TITLE
feat: add commitlint.config.*, eslint.config.*, i18n.config.*, ionic.config.json, .nuxtrc, nuxt.config.*, .prettierrc.*, .prettierignore, prettier.config.*

### PR DESCRIPTION
**Pull request by GR3YH4TT3R93**
Added:
- Commitlint
  - `commitlint.config.js`
  - `commitlint.config.ts`

- Eslint
  - `eslint.config.cjs`
  - `eslint.config.js`
  - `eslint.config.mjs`
  - `eslint.config.ts`

- I18n
  - `i18n.config.js`
  - `i18n.config.ts`

- Ionic
  - `ionic.config.json`

- Nuxt
  - `.nuxtrc`
  - `nuxt.config.cjs`
  - `nuxt.config.js`
  - `nuxt.config.mjs`
  - `nuxt.config.ts`

- Prettier
  - `.prettierrc.json`
  - `.prettierrc.json5`
  - `.prettierrc.toml`
  - `.prettierrc.yaml`
  - `.prettierrc.yml`
  - `.prettierignore`
  - `prettier.config.cjs`
  - `prettier.config.js`
  - `prettier.config.mjs`
  - `prettier.config.ts`

### CODE REVIEW

**Comment by GR3YH4TT3R93** [comment]
Force push was to correct order (i18n before i3 rather than after because 1 comes before 3 *duh*)

**Comment by GR3YH4TT3R93** [comment]
Force push was to correct order (i18n before i3 rather than after because 1 comes before 3 *duh*)

**Review by hasecilu — APPROVED** [review]
LGTM!
image

**Review by alex-courtis — APPROVED** [review]
Many thanks for your contribution @GR3YH4TT3R93 and many thanks @hasecilu for reviewing.

**Comment by alex-courtis** [comment]
Many thanks for all the diligent reviews @hasecilu 

I've update your rights: you should be able to merge after review.

**Comment by hasecilu** [comment]
> Many thanks for all the diligent reviews @hasecilu 
> 
> I've update your rights: you should be able to merge after review.

Hi, thanks for the trust! I'll be checking the project from time to time, I'm not a Lua expert so mainly will interact with icon additions.

**Comment by alex-courtis** [comment]
> > Many thanks for all the diligent reviews @hasecilu
> > I've update your rights: you should be able to merge after review.
> 
> Hi, thanks for the trust! I'll be checking the project from time to time, I'm not a Lua expert so mainly will interact with icon additions.

No pressure; anything from a trusted project member is most gratefully appreciated but not expected.

**Pull request merged**
