### PR TITLE
feat: Add Groovy icon

### PR DESCRIPTION
**Pull request by AlexandrosAlexiou**

### CODE REVIEW

**Comment by alex-courtis** [comment]
Holding off pending https://github.com/nvim-tree/nvim-web-devicons/pull/376

**Comment by AlexandrosAlexiou** [comment]
> Holding off pending #376

By the way, from where do you get the icons? (I am using [this](https://www.nerdfonts.com/cheat-sheet))

**Comment by alex-courtis** [comment]
> > Holding off pending #376
> 
> By the way, from where do you get the icons? (I am using [this](https://www.nerdfonts.com/cheat-sheet))

That's what we use.

As there's no seti for groovy, dev is the good choice.

**Review by alex-courtis — APPROVED** [review]
Many thanks for your contribution!

**Pull request merged**
