### PR TITLE
fix: remove dashes and underscores that seems to generate errors

### LINKED ISSUE #440: Invalid highlight name
Hello, 

I updated this morning my plugins, and now I get : 
```

Failed to run `config` for nvim-tree.lua

...re/nvim/lazy/nvim-web-devicons/lua/nvim-web-devicons.lua:286: Invalid highlight name: 'DevIconTrisquel_GNU-Linux
```
And sometimes I got the same message with : `Invalid highlight name: 'DevIconParabola_GNU-Linux_libre'`

Any idea ?

### PR DESCRIPTION
**Pull request by hasecilu**
Fix #440

### CODE REVIEW

**Comment by parkerkain-8451** [comment]
Thanks for the quick work on this @hasecilu - anecdotally the names mentioned in the diff are the same ones I'm seeing in my error messages!

**Review by gegoune — APPROVED** [review]

**Comment by gegoune** [comment]
I don't have any problem with neither `-` nor `_`. I am on 0.10, so perhaps it's different on 0.9? Could someone on stable confirm if those work:

```
:hi foo-bar gui=bold
:hi foo_bar gui=bold
```

(Both work on 0.10.) 

While `/` errors.

**Comment by hasecilu** [comment]
> I don't have any problem with neither `-` nor `_`. I am on 0.10, so perhaps it's different on 0.9? Could someone on stable confirm if those work:
> 
> ```
> :hi foo-bar gui=bold
> :hi foo_bar gui=bold
> ```
> 
> (Both work on 0.10.)
> 
> While `/` errors.

Same here but with NVIM v0.9.5, LuaJIT 2.1.1702233742.
For me dash and underscore work and slash fails.

**Comment by haakonfp** [comment]
on v0.9.4.

``:hi foo-bar gui=bold`` errors.
``:hi foo_bar gui=bold`` does not error.
``:hi foo/bar gui=bold`` also errors.

**Comment by meatballs** [comment]
Turns out I was still on 0.9.1 Updating to 0.9.5 solved the problems in #440

**Comment by gegoune** [comment]
Thanks for the fix @hasecilu.
Let's merge it in, group names look better that way anyway and it fixes backwards incompatibility.

**Pull request merged**
