### PR TITLE
Base-16 is now avaiable.

### PR DESCRIPTION
**Pull request by FrenzyExists**
Tweaking each individual icon is a pain, so instead, i decided to apply base-16 to color all icons, and allowed users to simply override a global map called `Colors`. Hope this saves some hastle!

### CODE REVIEW

**Review by kyazdani42 — COMMENTED** [review]
I'm unsure about this. Many icons already have specific colors that don't match the base16 here.
I'd like to get more user feedback before any decision is made towards this.

**Comment by FrenzyExists** [comment]
No prob :+1:

**Comment by alex-courtis** [comment]
As a base16 user I like the idea, however agree with @kyazdani42

**Comment by kyazdani42** [comment]
Let's close this, it's a bit old and it would change the display of most user configurations too drastically.

**Pull request closed without merging**
