### PR TITLE
dummy change to test CI

### PR DESCRIPTION
**Pull request by alex-courtis**

### CODE REVIEW

**Comment by alex-courtis** [comment]
@gegoune CI is running, however there are a couple of issues:
1. not run for PR branches, like this one
2. (manual run) failed as it's missing dependencies: https://github.com/nvim-tree/nvim-web-devicons/actions/runs/4463802207

**Comment by alex-courtis** [comment]
I'm keen to get this into nvim-tree once we've got it all working here.

**Comment by gegoune** [comment]
https://github.com/nvim-tree/nvim-web-devicons/pull/235 should fix point 2.
Point 1: this is scheduled run, it will run daily, not on branches/PRs unless manually triggered.

**Comment by alex-courtis** [comment]
> #235 should fix point 2. Point 1: this is scheduled run, it will run daily, not on branches/PRs unless manually triggered.

Fantastic! Tasks all running successfully with nice output: https://github.com/nvim-tree/nvim-web-devicons/actions/runs/4475379933/jobs/7864741163#step:11:231

Unfortunately create-pull-request is failing; what should that be doing? I'm happy enough with the checks :)

**Comment by alex-courtis** [comment]
> Point 1: this is scheduled run, it will run daily, not on branches/PRs unless manually triggered.

Should we do this for PRs? It would be very useful for users that haven't updated / checked the generated colours.

**Comment by gegoune** [comment]
Yes, definitely.

**Comment by alex-courtis** [comment]
Looking good so far: see #239  #240

**Pull request closed without merging**
