### PR TITLE
feat: add build.zig.zon

### PR DESCRIPTION
**Pull request by pseudocc**
ziglang/zig#14290

### CODE REVIEW

**Comment by alex-courtis** [comment]
Seti icon looks good.

Should we be using simply `zig.zon` rather than build? Is it a general zig file extension?

**Comment by pseudocc** [comment]
By far, Zig(v0.11.0) does not provide a simple way to parse zon file, even parsing [build.zig.zon](https://github.com/ziglang/zig/blob/0.11.0/src/Manifest.zig#L146) is kinda hard coded.

To me, both "build.zig.zon" and "*.zig.zon" are good. Sorry for the late reply, I am enjoying Chinese New Year now.

**Comment by alex-courtis** [comment]
> By far, Zig(v0.11.0) does not provide a simple way to parse zon file, even parsing [build.zig.zon](https://github.com/ziglang/zig/blob/0.11.0/src/Manifest.zig#L146) is kinda hard coded.
> 
> To me, both "build.zig.zon" and "*.zig.zon" are good. Sorry for the late reply, I am enjoying Chinese New Year now.

Understood. Hardcoded build it is.

GXFC

**Comment by hornyjailfish** [comment]
broken! remove spaces inside hl name string

**Comment by zyriab** [comment]
Hey guys, this broke my Neovim :(
image

**Comment by zyriab** [comment]
I opened #397 :)

**Comment by rafamancan** [comment]
> I opened #397 :)

I made your modification on my config and works fine!
Thx.

**Comment by alex-courtis** [comment]
Many thanks for the quick fix @zyriab

**Comment by zyriab** [comment]
> Many thanks for the quick fix @zyriab

Cheers :)

**Pull request merged**
