### PR TITLE
feat: Add README icons

### PR DESCRIPTION
**Pull request by DreepyYunky**
READMEs (eg `README.md`) are special files, so giving them special icon can help distinct them from, for example, an average markdown file.

The icon is `nf-md-information` which I think fits since READMEs give information about the thing it's on.

### CODE REVIEW

**Comment by alex-courtis** [comment]
Holding off pending #376

**Comment by DreepyYunky** [comment]
> Holding off pending #376

Ok.

**Comment by pauchiner** [comment]
@DreepyYunky i think you should also add for `.rst` README files, these are pretty common in python enviroments

**Comment by DreepyYunky** [comment]
> @DreepyYunky i think you should also add for `.rst` README files, these are pretty common in python enviroments

I even might add for files just named `README`, no txt or md.

**Comment by DreepyYunky** [comment]
@pauchiner Added `.rst`s now.

**Comment by alex-courtis** [comment]
Sorry, I don't think we should do this: markdown and text are file types, readme is not. web-devicons only handles types, particularly those specified by languages.

That's kind of confirmed by the lack of readme icon in nerd fonts ;)

If you desire special file name handling you can use API `override_by_filename`

**Pull request closed without merging**
