### PR TITLE
fix: vue icon

### PR DESCRIPTION
**Pull request by philopence**

### CODE REVIEW

**Review by alex-courtis — APPROVED** [review]
Thank you for your contribution

**Comment by zLinz** [comment]
The vue file icon now is question mark?
image

**Comment by alex-courtis** [comment]
Looks similar to the previous in alacritty with Hack Nerd Font Mono



Which font/terminal are you using?

**Comment by gegoune** [comment]
I am getting placeholder icon instead in Wezterm using built in Nerd Font fallback mechanism.

What was reasoning behind that change?

**Comment by gegoune** [comment]
@philopence Does that glyph come from some additional font pack?

**Comment by alex-courtis** [comment]
I'll just revert this for now; we can re-apply once we sort out the root of the issue.

**Pull request merged**
