### PR TITLE
Add typst logo as .typ

### PR DESCRIPTION
**Pull request by Parsifa1**
add [typst](https://typst.app/).
the "scad" change due to the `make` generated .

### CODE REVIEW

**Comment by alex-courtis** [comment]
It doesn't look like `𝐭` is part of nerd fonts https://www.nerdfonts.com/cheat-sheet and thus may not be available to all.

Can you pick one from there? Preferably seti.

**Comment by Parsifa1** [comment]
It seems that typst does not yet have a corresponding nerd font symbol(with seti), and may have to wait for upstream improvements,Sorry.

**Comment by alex-courtis** [comment]
No worries... please do come back when it's added.

**Comment by kamack38** [comment]
It seems that the typst logo will be included when the `v3.3.0` version of Nerd Fonts drops. (https://github.com/ryanoasis/nerd-fonts/issues/1682#issuecomment-2399474257)

**Pull request closed without merging**
