### PR TITLE
docs(#516): README: full description

### LINKED ISSUE #516: The repo description should state what the plugin does rather than just stating its a fork
I had made a [discussion post](https://github.com/nvim-tree/nvim-web-devicons/discussions/508) and one [on Reddit](https://new.reddit.com/r/neovim/comments/1gix7m2/overriding_specific_nerd_icons_in_nvimwebdevicons/) asking how to override individual nvim-web-icons, mistakenly thinking that it serves any nerd font icon, and only found out recently that the plugin is specifically for filetype icons. I think the repo description should change to something like "A plugin for serving filetype icons, forked from vim-devicons"

### PR DESCRIPTION
**Pull request by alex-courtis**
fixes #516

### CODE REVIEW

**Comment by hasecilu** [comment]
Also would be good to update the About and add mote tags, maybe: icons, neovim, lua, plugin

image

**Comment by alex-courtis** [comment]
Great idea!

**Comment by Oneechan69** [comment]
@alex-courtis So far it looks good, but does the plugin provide all nerd font icons and overrides? If not then I think the readme should state that.

**Comment by alex-courtis** [comment]
> @alex-courtis So far it looks good, but does the plugin provide all nerd font icons and overrides? If not then I think the readme should state that.

Maybe some better phrasing.

The icons it provides by default are a subset of nerd fonts. You can override with whatever you please.

Proposed about:
> Provides icons (glyphs) for use by neovim plugins. Nerd Font icons are provided for a set of file extensions and names.

**Comment by hasecilu** [comment]
> Provides Nerd Font[^1] icons (glyphs) associations with filetypes for use by Neovim plugins.


[^1]: Not limited to use Nerd Font icons, there is even a Unicode glyph used, even there are people that have custom fonts

**Comment by hasecilu** [comment]
> @alex-courtis So far it looks good, but does the plugin provide all nerd font icons and overrides? If not then I think the readme should state that.

I don't think that's important, I think it's evident that not all filetypes and filenames will be covered, certainly is desirable. Not even Nerd Fonts has a list of filetypes/filenames they "just" gather the fonts, actually this project is one of the most complete projects with icons associations and to really achieve the "complete set of overrides" would be needed the help of lot of people, meanwhile I have a small change in progress.

**Comment by alex-courtis** [comment]
Updated. Many thanks!

**Pull request merged**
