### PR TITLE
fix: broken .prettierrc icon

### PR DESCRIPTION
**Pull request by xuanhung1509**

### CODE REVIEW

**Comment by gegoune** [comment]
Please merge with https://github.com/nvim-tree/nvim-web-devicons/pull/481 (and close #481). Could you also describe what's broken?

THanks!

**Comment by xuanhung1509** [comment]
The icon cannot be displayed correctly. I've tried copying the icon from [NerdFonts](https://www.nerdfonts.com/cheat-sheet) and it's the same.

image
image

Sorry for creating 2 separate PR, as I randomly comes thru the issue and directly create PR from GitHub.

**Comment by alex-courtis** [comment]
Are you sure your nerdfont is up to date @xuanhung1509 ?

This icon was very recently added in 3.2.0: https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.2.0

**Comment by xuanhung1509** [comment]
I use JetBrainsMonoNerdFont, and I don't see my nerd font in the update list. I find prettier icon and paste into my terminal and it still showing an empty rectangle.

And this is your icons-default.lua
image

**Comment by alex-courtis** [comment]
It sounds like it's your font. Looking at the AUR distribution for that font it is up to date with 3.2:

```
: ; yay -Ss jetbrains patch nerd
extra/ttf-jetbrains-mono-nerd 3.2.1-2 (9.7 MiB 204.3 MiB) [nerd-fonts]
    Patched font JetBrains Mono from nerd fonts library
```

Testing with alacritty all OK. Sorry, you'll need to fix your font.

**Pull request closed without merging**
