### PR TITLE
fix(exe): invalid hex value

### PR DESCRIPTION
**Pull request by gegoune**
https://github.com/nvim-tree/nvim-web-devicons/pull/351#issuecomment-1866252468

### CODE REVIEW

**Comment by jalada** [comment]
Damn my bad luck running `:PlugUpdate` 5 minutes ago!

Thanks for fixing 🙏🏻

**Comment by pysan3** [comment]
Thanks @gegoune for your quick response!

**Comment by hulander** [comment]
> Damn my bad luck running `:PlugUpdate` 5 minutes ago!

I also updated right after the merge 😅

Thanks @gegoune for the quick fix!

**Comment by gegoune** [comment]
Apologies for the disturbance, CI was all green and I tested it locally on light theme only.

**Pull request merged**
