### PR TITLE
feat: add adb ads gpr

### PR DESCRIPTION
**Pull request by nerdtype**
Add icon for '.adb', '.ads', and '.gpr' file types.

### CODE REVIEW

**Review by alex-courtis — CHANGES_REQUESTED** [review]
Can we please use the ada icon?

`nf-custom-ada`

https://www.nerdfonts.com/cheat-sheet

**Comment by nerdtype** [comment]
From an end-user perspective- as an Ada software developer using nvim (with nvim-tree), what would add value to me is being able to differentiate between the primary Ada source files and indicate the particular function of the files.

In Ada, this can be summarized to the following files:

.adb - Body
.ads - Specification
.gpr - GNAT GPRBuild project

To this end, I have selected icons which visually align with the function of the file being represented and would prefer to keep those selected.

**Comment by alex-courtis** [comment]
> From an end-user perspective- as an Ada software developer using nvim (with nvim-tree), what would add value to me is being able to differentiate between the primary Ada source files and indicate the particular function of the files.

web-devicons provides the actual icons for file types, rather than abstract arbitrary icons.

Suggestions:
1. Use colours to differentiate the icons for adb, ads...
2. Provide your custom icons via setup/api https://github.com/nvim-tree/nvim-web-devicons?tab=readme-ov-file#setup

**Comment by nerdtype** [comment]
If you we going to use a font glyph to represent Ada file types, we should at least use the latest and (most popular) Ada logo:

https://blog.adacore.com/our-contribution-to-the-ada-logo-discussion

image

**Review by alex-courtis — APPROVED** [review]
Many thanks for your contribution!

**Comment by nerdtype** [comment]
Thanks Alex!

**Pull request merged**
